/**
 * OracleChat — The simulated conversation window for the Multiverse Scene Tester.
 *
 * This component renders the dialogue between two AI character agents.
 * It's the "Oracle" View described in the feature spec — the place where
 * the writer watches the agents interact and sees the Truth Guard in action.
 *
 * VISUAL DESIGN
 * ─────────────
 * - Each dialogue turn uses the `inkFlow` animation preset (text appears
 *   as if being written by ink on parchment).
 * - Turns from different characters are visually distinguished by
 *   alignment (left vs. right) and border color.
 * - Paradox violations get a pulsing red border (paradoxPulse animation).
 * - Epistemic "knowledge badges" show what each character knows/doesn't
 *   know, collapsible to save space.
 *
 * CONSTRAINTS
 * ───────────
 * - This component NEVER generates prose. It only displays dialogue
 *   generated by the backend agents.
 * - The "Mark Decision" button lets the writer manually flag a moment
 *   as a fork point, in addition to the automatic detection.
 */

"use client";

import { useRef, useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { multiverseMotion } from "@/lib/sori-motion";
import type { DialogueTurn, EpistemicProfile } from "@/types/multiverse";

// ============================================================
// PROPS
// ============================================================

interface OracleChatProps {
  /** The dialogue turns to display, in chronological order */
  turns: DialogueTurn[];

  /**
   * Epistemic profiles for the two characters in this simulation.
   * Used to render the "knowledge badge" that shows what each character
   * knows and doesn't know. null if profiles haven't loaded yet.
   */
  profiles: [EpistemicProfile, EpistemicProfile] | null;

  /** Whether the simulation is currently running (agents are "talking") */
  isSimulating: boolean;

  /**
   * Callback when the writer manually marks the current dialogue point
   * as a decision point. This triggers the branching UI to appear.
   */
  onMarkDecision: () => void;
}

// ============================================================
// COMPONENT
// ============================================================

export function OracleChat({
  turns,
  profiles,
  isSimulating,
  onMarkDecision,
}: OracleChatProps) {
  // Auto-scroll to the bottom when new turns arrive.
  // We use a ref to the scroll container and scrollIntoView on updates.
  const scrollAnchorRef = useRef<HTMLDivElement>(null);
  const [showKnowledge, setShowKnowledge] = useState(false);

  useEffect(() => {
    // Scroll to the newest dialogue turn whenever the turn count changes.
    // The slight delay ensures the DOM has rendered the new turn before
    // we scroll to it (Framer Motion animations need a frame).
    const timer = setTimeout(() => {
      scrollAnchorRef.current?.scrollIntoView({ behavior: "smooth" });
    }, 100);
    return () => clearTimeout(timer);
  }, [turns.length]);

  // Determine which character is "left" and which is "right" in the chat.
  // The first character to speak goes on the left (visually consistent
  // across the entire conversation).
  const firstCharId = turns.length > 0 ? turns[0].characterId : null;

  return (
    <div className="flex flex-col">
      {/* ── Header ── */}
      <div className="flex items-center justify-between border-b border-[var(--sori-border)] px-4 py-3">
        <div>
          <p className="sori-kicker text-[10px]">oracle view</p>
          <h3 className="mt-1 font-[family-name:var(--font-display)] text-lg tracking-tight">
            Agent Dialogue
          </h3>
        </div>
        <div className="flex gap-2">
          {/* Knowledge toggle — lets the writer see/hide epistemic badges */}
          <button
            onClick={() => setShowKnowledge(!showKnowledge)}
            className="sori-chip rounded-full px-3 py-1 transition-colors hover:bg-[var(--sori-bg-secondary)]"
          >
            {showKnowledge ? "hide knowledge" : "show knowledge"}
          </button>
        </div>
      </div>

      {/* ── Knowledge Badges (collapsible) ── */}
      <AnimatePresence>
        {showKnowledge && profiles && (
          <motion.div
            {...multiverseMotion.inkFlow}
            exit={{ opacity: 0, y: -8 }}
            className="border-b border-[var(--sori-border)] px-4 py-3"
          >
            <div className="grid grid-cols-2 gap-3">
              {profiles.map((profile) => (
                <KnowledgeBadge key={profile.characterId} profile={profile} />
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Dialogue Turns ── */}
      <div className="hide-scrollbar flex-1 overflow-y-auto px-4 py-4">
        {turns.length === 0 && !isSimulating && (
          <div className="flex h-full items-center justify-center">
            <p className="text-center text-sm text-[var(--sori-text-muted)]">
              Start a simulation to see agents interact here.
              <br />
              <span className="mt-1 block text-xs">
                Each agent only knows what the Truth Guard allows.
              </span>
            </p>
          </div>
        )}

        <AnimatePresence mode="popLayout">
          {turns.map((turn) => (
            <DialogueBubble
              key={turn.id}
              turn={turn}
              isLeft={turn.characterId === firstCharId}
            />
          ))}
        </AnimatePresence>

        {/* Simulating indicator — three dots animation */}
        {isSimulating && (
          <motion.div
            {...multiverseMotion.inkFlow}
            className="mt-3 flex items-center gap-2 text-sm text-[var(--sori-text-muted)]"
          >
            <SimulatingDots />
            <span>Agents are interacting...</span>
          </motion.div>
        )}

        {/* Invisible scroll anchor — always at the bottom */}
        <div ref={scrollAnchorRef} />
      </div>

      {/* ── Footer Actions ── */}
      {turns.length > 0 && !isSimulating && (
        <div className="border-t border-[var(--sori-border)] px-4 py-3">
          <button
            onClick={onMarkDecision}
            className="w-full rounded-[1rem] border border-[var(--sori-border)] bg-[var(--sori-bg-secondary)] px-4 py-2.5 text-sm font-medium transition-all hover:border-[var(--sori-accent-coral)] hover:bg-[var(--sori-bg-surface)]"
          >
            Mark as Decision Point
          </button>
        </div>
      )}
    </div>
  );
}


// ============================================================
// DIALOGUE BUBBLE — A single turn of conversation
// ============================================================

/**
 * Renders one dialogue turn as a chat bubble.
 *
 * Left-aligned bubbles represent the first character to speak.
 * Right-aligned bubbles represent the second character.
 *
 * Paradox turns get a red border and a pulsing glow animation
 * to immediately draw the writer's attention to the violation.
 */
function DialogueBubble({
  turn,
  isLeft,
}: {
  turn: DialogueTurn;
  isLeft: boolean;
}) {
  return (
    <motion.div
      {...multiverseMotion.inkFlow}
      className={`mb-3 flex ${isLeft ? "justify-start" : "justify-end"}`}
    >
      <motion.div
        // Apply paradox pulse animation only if this turn has a violation
        {...(turn.isParadox ? multiverseMotion.paradoxPulse : {})}
        className={`
          relative max-w-[85%] rounded-[1.1rem] border p-3
          ${
            turn.isParadox
              ? "border-destructive/40 bg-destructive/5"
              : isLeft
                ? "border-[var(--sori-border)] bg-[var(--sori-bg-surface)]"
                : "border-[var(--sori-accent-sage)]/30 bg-[var(--sori-accent-sage)]/5"
          }
        `}
      >
        {/* Character name label */}
        <p className="sori-kicker mb-1.5 text-[9px]">
          {turn.characterName}
        </p>

        {/* The actual dialogue content */}
        <p className="m-0 text-sm leading-relaxed text-[var(--sori-text-primary)]">
          {turn.content}
        </p>

        {/* Paradox warning badge */}
        {turn.isParadox && turn.paradoxDetail && (
          <div className="mt-2 rounded-[0.7rem] border border-destructive/30 bg-destructive/10 px-2.5 py-1.5">
            <p className="m-0 text-[10px] font-medium uppercase tracking-[0.14em] text-destructive">
              Structural Paradox
            </p>
            <p className="m-0 mt-0.5 text-xs text-destructive/80">
              {turn.paradoxDetail}
            </p>
          </div>
        )}
      </motion.div>
    </motion.div>
  );
}


// ============================================================
// KNOWLEDGE BADGE — Shows what a character knows/doesn't know
// ============================================================

/**
 * Compact display of a character's epistemic state.
 *
 * Shows the character name, their role, and a summary of how many
 * facts they know vs. don't know. Expandable to show the full list.
 */
function KnowledgeBadge({ profile }: { profile: EpistemicProfile }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="rounded-[0.9rem] border border-[var(--sori-border)] bg-[var(--sori-bg-surface)] p-2.5">
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex w-full items-center justify-between text-left"
      >
        <div>
          <p className="m-0 text-xs font-medium text-[var(--sori-text-primary)]">
            {profile.characterName}
          </p>
          {profile.roleHint && (
            <p className="m-0 text-[10px] text-[var(--sori-text-muted)]">
              {profile.roleHint}
            </p>
          )}
        </div>
        <div className="flex gap-1.5 text-[10px]">
          <span className="rounded-full bg-[var(--sori-accent-sage)]/15 px-1.5 py-0.5 text-[var(--sori-accent-sage)]">
            {profile.knownFacts.length} known
          </span>
          <span className="rounded-full bg-[var(--sori-accent-lavender)]/15 px-1.5 py-0.5 text-[var(--sori-accent-lavender)]">
            {profile.unknownFacts.length} hidden
          </span>
        </div>
      </button>

      {/* Expanded fact list */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="overflow-hidden"
          >
            <div className="mt-2 space-y-1 border-t border-[var(--sori-border)] pt-2">
              {profile.knownFacts.length > 0 && (
                <div>
                  <p className="m-0 text-[9px] font-medium uppercase tracking-[0.14em] text-[var(--sori-accent-sage)]">
                    Knows
                  </p>
                  {profile.knownFacts.map((fact) => (
                    <p
                      key={fact.factNodeId}
                      className="m-0 text-[10px] leading-snug text-[var(--sori-text-secondary)]"
                    >
                      • {fact.description}
                    </p>
                  ))}
                </div>
              )}
              {profile.unknownFacts.length > 0 && (
                <div className="mt-1.5">
                  <p className="m-0 text-[9px] font-medium uppercase tracking-[0.14em] text-[var(--sori-accent-lavender)]">
                    Does Not Know
                  </p>
                  {profile.unknownFacts.slice(0, 5).map((fact) => (
                    <p
                      key={fact.factNodeId}
                      className="m-0 text-[10px] leading-snug text-[var(--sori-text-muted)]"
                    >
                      • {fact.description}
                    </p>
                  ))}
                  {profile.unknownFacts.length > 5 && (
                    <p className="m-0 text-[10px] text-[var(--sori-text-muted)]">
                      + {profile.unknownFacts.length - 5} more...
                    </p>
                  )}
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}


// ============================================================
// SIMULATING DOTS — Three-dot loading animation
// ============================================================

/**
 * A simple three-dot "typing" indicator used while agents are
 * generating dialogue. Each dot bounces in sequence.
 */
function SimulatingDots() {
  return (
    <span className="flex gap-1">
      {[0, 1, 2].map((i) => (
        <motion.span
          key={i}
          className="inline-block h-1.5 w-1.5 rounded-full bg-[var(--sori-accent-coral)]"
          animate={{ y: [0, -4, 0] }}
          transition={{
            duration: 0.6,
            repeat: Infinity,
            delay: i * 0.15,
            ease: "easeInOut",
          }}
        />
      ))}
    </span>
  );
}
