"""
Story graph models — the writing platform layer (v2 frontend, v1 schema).

These nodes are dormant in v1 but exist in the schema so that:
1. The LLM output format is future-proof (scaffolds are already StoryNodes)
2. User-generated stories can feed back into the knowledge graph
3. The Architect mode canvas has proper data structures from day one

Architecture:
    StoryNode — container for a user's story
        → SceneNode — individual scenes (nodes on the Twine-like canvas)
            → NarrativeEdge — connections between scenes (edges on canvas)

    SceneNodes link back to ConceptNodes via FULFILLS, creating a bridge
    between the knowledge graph and user-generated content.
"""
from neomodel import (
    ArrayProperty,
    StructuredNode,
    StructuredRel,
    StringProperty,
    IntegerProperty,
    JSONProperty,
    FloatProperty,
    DateTimeProperty,
    RelationshipTo,
    RelationshipFrom,
    UniqueIdProperty,
)


class StoryNode(StructuredNode):
    """A user-created story. Container for the scene graph."""

    uid = UniqueIdProperty()
    title = StringProperty(required=True)
    owner_id = StringProperty(required=True)  # contributor uid

    # Story parameters the agent used for scaffold generation
    genre = StringProperty()
    protagonist_archetype = StringProperty()
    central_conflict = StringProperty()
    additional_params = JSONProperty(default={})

    # Which version of the knowledge graph generated this scaffold
    knowledge_graph_version = StringProperty()

    status = StringProperty(
        choices={
            "scaffolded": "Structural scaffold generated",
            "in_progress": "Writer is working on scenes",
            "first_draft": "All scenes have content",
            "complete": "Writer marked as complete",
        },
        default="scaffolded",
    )

    created_at = DateTimeProperty(default_now=True)
    updated_at = DateTimeProperty(default_now=True)

    # Relationships
    scenes = RelationshipTo("SceneNode", "CONTAINS_SCENE")


class SceneNode(StructuredNode):
    """A scene in the user's story graph — a node on the Twine-like canvas.

    In v1 (Architect mode): displays the scene brief and concept provenance.
    In v2 (Writer mode): opens into a rich text editor for prose.
    """

    uid = UniqueIdProperty()
    title = StringProperty(required=True)

    # Structural placement
    act = StringProperty()  # "act_1", "act_2a", "midpoint", "act_2b", "act_3"
    beat_type = StringProperty()  # "call_to_adventure", "dark_night_of_soul", etc.
    sequence_order = IntegerProperty(default=0)

    # Scene brief — generated by the agent from knowledge graph
    brief = StringProperty()  # What this scene needs to accomplish
    emotional_temperature = FloatProperty()  # -1 (despair) to 1 (triumph)
    concept_node_ids = JSONProperty(default=[])  # Which concepts generated this brief

    # Trope warnings — structural gravity alerts
    trope_warnings = JSONProperty(default=[])
    # e.g., [{"trope": "mentor_death_as_catalyst", "probability": 0.87,
    #         "note": "High probability given your character setup"}]

    # Canvas position (for React Flow rendering)
    position_x = FloatProperty(default=0.0)
    position_y = FloatProperty(default=0.0)

    # Content (v2 — prose goes here)
    content = StringProperty(default="")

    created_at = DateTimeProperty(default_now=True)
    updated_at = DateTimeProperty(default_now=True)

    # Relationships
    story = RelationshipFrom(StoryNode, "CONTAINS_SCENE")
    fulfills = RelationshipTo(
        "graph.models.knowledge.ConceptNode", "FULFILLS"
    )
    # Narrative edges — typed connections between scenes
    leads_to = RelationshipTo("SceneNode", "LEADS_TO")
    branches_to = RelationshipTo("SceneNode", "BRANCHES_TO")
    flashes_back_to = RelationshipTo("SceneNode", "FLASHES_BACK_TO")
    parallels = RelationshipTo("SceneNode", "PARALLELS")


# ============================================================
# Epistemic tracking — who knows what, when
# ============================================================


class TemporalRel(StructuredRel):
    """Edge properties for KNOWS_AT and ACTS_ON relationships.

    beat_index is 1-based and corresponds to outline line numbers so the
    frontend can highlight the exact beat where a violation occurs.
    """

    beat_index = IntegerProperty(required=True)
    confidence = FloatProperty(default=0.7)
    source = StringProperty(default="heuristic")


class CharacterNode(StructuredNode):
    """A named character extracted from a writer's outline.

    Scoped to a single story via story_uid. The epistemic module creates
    these during analysis and links them to StoryFactNodes via temporal edges.
    """

    uid = UniqueIdProperty()
    name = StringProperty(required=True, index=True)
    story_uid = StringProperty(required=True, index=True)
    aliases = ArrayProperty(StringProperty(), default=[])
    role_hint = StringProperty()

    created_at = DateTimeProperty(default_now=True)

    knows = RelationshipTo("StoryFactNode", "KNOWS_AT", model=TemporalRel)
    acts_on = RelationshipTo("StoryFactNode", "ACTS_ON", model=TemporalRel)


class StoryFactNode(StructuredNode):
    """A discrete piece of story information that characters can learn or act on.

    Examples: "the father wrote apology letters", "the witness is alive",
    "the detective's partner is the mole". Each fact is introduced at a
    specific beat and may be learned by characters at different beats.
    """

    uid = UniqueIdProperty()
    story_uid = StringProperty(required=True, index=True)
    description = StringProperty(required=True)
    introduced_at_beat = IntegerProperty(required=True)
    fact_type = StringProperty(default="information")

    created_at = DateTimeProperty(default_now=True)

    known_by = RelationshipFrom("CharacterNode", "KNOWS_AT", model=TemporalRel)
    acted_on_by = RelationshipFrom("CharacterNode", "ACTS_ON", model=TemporalRel)
